spring:
  messages:
    basename: translations
  jackson:
    serialization:
      write_dates_as_timestamps: false
  profiles:
    active: dev
  mandatory-file-encoding: utf-8 #кодировка файлов на диске(при необходимости);
logging:
  level:
    ROOT: INFO
---
jwt:
  secretKey: "somekey"
  tokenValidityInMilliseconds: 86400000
  tokenValidityInMillisecondsForRememberMe: 2592000000
---
#порт по умолчанию;
server:
  port: 8080
---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      temp.use_jdbc_metadata_defaults: false
      show_sql: false
      format_sql: true
      enable_lazy_load_no_trans: true #If you would like to keep Lazy Load and you are using Spring Boot
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticketbus
    username: root
    password: root
---
spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 465
    username: ospreystudio2018@gmail.com
    password: osprey2018
    protocol: smtps
---
spring:
  profiles: devdisable
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect #https://stackoverflow.com/questions/49680199/java-lang-reflect-invocationtargetexception-null
      temp.use_jdbc_metadata_defaults: false
      show_sql: true
      format_sql: true
      enable_lazy_load_no_trans: true #If you would like to keep Lazy Load and you are using Spring Boot
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  #Monitoring
  management:
    endpoints:
      web:
        exposure:
          include:
          - beans
          - health
          - metrics
          - env
---
spring:
  profiles: test
  flyway:
    enabled: false

---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: create
    properties.hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: true
      format_sql: true
    database-platform: H2
  flyway:
    enabled: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
