-- users_tbl
drop table users_tbl if exists;

create table users_tbl (
  id bigint generated by default as identity,
  active boolean,
  email varchar(100) not null,
  fist_name varchar(100) not null,
  last_name varchar(100) not null,
  password varchar(100) not null,
  primary key (id)
);

alter table users_tbl
  add constraint email_unique unique (email);

-- user2roles_tbl
drop table user2roles_tbl if exists;

create table user2roles_tbl (
  user_id bigint not null,
  roles_enum varchar(20) not null,
  primary key (user_id, roles_enum)
);

alter table user2roles_tbl
  add constraint users2roles_user_fk foreign key (user_id) references users_tbl;
``
-- token_tbl
drop table token_tbl if exists;

create table token_tbl (
  id bigint generated by default as identity,
  session varchar(100) not null,
  user_id bigint not null,
  primary key (id)
);

alter table token_tbl
  add constraint session_unique unique (session);

alter table token_tbl
  add constraint token_unique unique (session, user_id);

alter table token_tbl
  add constraint token_users_fk foreign key (user_id) references users_tbl;

-- tickets_tbl
drop table tickets_tbl if exists;

create table tickets_tbl (
  id bigint generated by default as identity,
  purchase_date timestamp not null,
  ticket_number integer not null,
  user_id bigint,
  primary key (id)
);

alter table tickets_tbl
  add constraint ticket_number_unique unique (ticket_number);

alter table tickets_tbl
  add constraint ticket_user_fk foreign key (user_id) references users_tbl;